### ISSUE TITLE
Downloading K-MER POSITION ENTROPY data from DiMA

### ISSUE THREAD

**Issue by vguerracanedo** [eselimnl/dima#2]

**Comment by eselimnl** [comment]
Hi Vanessa, 

We are delighted to receive your feedback.

Entropy data for each k-mer position can be downloaded in an xlsx format by adding the -f xlsx command when using [DiMA-CLI](https://github.com/BVU-BILSAB/DiMA). Alternatively, you can also download the xlsx results from the web server by clicking on the upper-left corner.

Thank you for reporting the negative entropy issue. We fixed the problem a while ago, so I believe you might have used our old web server. Please try our latest server available at [dima.bezmialem.edu.tr](https://dima.bezmialem.edu.tr/).

Feel free to inform us of any other issues.
